#!/usr/bin/php
<?php
require __DIR__.'/vendor/autoload.php';

$settings = include  __DIR__.'/config/config.php';
$settings['dir'] = __DIR__;

$reports = new \App\ImageReports($settings);

$line = readline('Enter domain ');

if ($line === 'all'){
    $reports->listDomains();
}else{
    $reports->getDomainFile($line);
}
